name: Run Docker Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest

    env:
      ENV: test
      SECRET_KEY: testsecret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      PYTHONPATH: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker containers
        run: |
          docker compose build

      - name: Run tests inside Docker
        run: |
          docker compose run --rm web pytest -v

      - name: Stop containers
        if: always()
        run: |
          docker compose down